version: "3.8"

services:
  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
      ACCESS_TOKEN_SECRET: your_access_token_secret_here_change_in_production
      REFRESH_TOKEN_SECRET: your_refresh_token_secret_here_change_in_production
      SESSION_SECRET: your_session_secret_here_change_in_production
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3001:3001"
    networks:
      - pomodoro-network
    volumes:
      - ./server/prisma:/app/prisma

  # Frontend Client (Development mode for now)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:3001/api/v1
      VITE_APP_NAME: Tempo
      VITE_APP_VERSION: 1.0.0
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - pomodoro-network

  # Nginx Reverse Proxy (for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - server
      - client
    networks:
      - pomodoro-network

networks:
  pomodoro-network:
    driver: bridge
